version: "3.8"

services:
  namenode:
    image: hadoopgroup5:latest
    networks:
      - hbase
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    command: ["hdfs", "namenode"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de
      labels:
        traefik.docker.network: hbase
        traefik.port: 9870
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9870"]
      interval: 30s
      timeout: 10s
      retries: 5

  datanode:
    image: hadoopgroup5:latest
    networks:
      - hbase
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    command: ["hdfs", "datanode"]
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: hbase
        traefik.port: 9864

  resourcemanager:
    image: hadoopgroup5:latest
    networks:
      - hbase
    env_file:
      - ./hadoop.env
    command: ["yarn", "resourcemanager"]
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de
      labels:
        traefik.docker.network: hbase
        traefik.port: 8088
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/ws/v1/cluster/info"]
      interval: 30s
      timeout: 10s
      retries: 5

  nodemanager:
    image: hadoopgroup5:latest
    networks:
      - hbase
    env_file:
      - ./hadoop.env
    command: ["yarn", "nodemanager"]
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: hbase
        traefik.port: 8042

  historyserver:
    image: hadoopgroup5:latest
    networks:
      - hbase
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    env_file:
      - ./hadoop.env
    command: ["mapred", "historyserver"]
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.hostname == akswnc4.aksw.uni-leipzig.de
      labels:
        traefik.docker.network: hbase
        traefik.port: 8188
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8188/ws/v1/history/mapreduce/jobs"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  datanode:
  namenode:
  hadoop_historyserver:

networks:
  hbase:
    external: true
